### ISSUE TITLE
email migration broke snapshot reviewer

### ISSUE THREAD

**Issue by ddemaio** [boombatower/tumbleweed-review#9]
Hi @boombatower I hope all is well. We when through an email migration just recently and the reviews stopped. The URL used to generate something like opensuse-factory/2020-11/msg00113.html, but now it generates a URL that's something like https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/6NLC2T3VJ27BXG5KMGMEH4LXDRHE2MSR/, which I think effects the script. I was looking at the code below and thought this might be the reason for why the emails stopped, but I really don't know nor would I have a clue how to update a script that can capture the new url format for the mail.

MAILING_LIST = 'opensuse-factory'
MAILING_LIST_URL = 'https://lists.opensuse.org/{list}/{year}-{month}/msg{number:05d}.html'
MAILBOX_URL = 'https://lists.opensuse.org/{list}/{list}-{year}-{month}.mbox.gz'
RELEASE_PATTERN = r'^\[{list}\] New Tumbleweed snapshot (?P<version>\d+) released!$'
RELEASE_PATTERN_SHORT = r'^New Tumbleweed snapshot (?P<version>\d+)( released!)?$'

This is in mail.py

**Comment by boombatower** [comment]
Hmm, I do not see an equivalent mbox file referenced on the new archives. The [old one](https://lists.opensuse.org/opensuse-factory/opensuse-factory-2020-11.mbox.gz) appears to still be there, but it is not updated since the switch over. Without a similar file I would have to rewrite the tool to crawl the archive web pages or subscribe on a _bot_ email address to generate an mbox locally. Do you know if there is any intention to offer a downloaded archive?

Also unless the links are generated based on a message ID or similar header it may no longer be possible to make links. Perhaps someone involved in the migration could chime in on this.

**Comment by bbreinbauer** [comment]
Looking at the archive of the list (https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/2020/10/), I found there is a download button for every month. For example for Oct. 2020 the link is:
https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/export/factory@lists.opensuse.org-2020-11.mbox.gz?start=2020-10-01&end=2020-11-01
The naming convention of the file is a little awkward...

Maybe this file can be used to re-enable the reviewer?

**Comment by ddemaio** [comment]
Thanks @boombatower I'm not exactly sure how that would look or where it would need import. I heard cboltz sent some info to you about it. Would the heroes need to integrate is can the code pull the list?

**Comment by boombatower** [comment]
Yeah, I think the mbox download URL should solve the primary problem, but will not allow for making links to the emails. I am fine with making that work, but I have had a variety of distractions keeping me from this. I'm sure I'll eventually get to it and apologize for the delay.

**Comment by boombatower** [comment]
I pushed 8f7b0b5f02957797b77e9a01b63e8d5ce337d174 which fixes the issue. The migration made for quite some fun.

**Comment by ddemaio** [comment]
Thank you @boombatower. Enjoy your holidays.
